### ISSUE TITLE
Drug Overviews: study phase

### ISSUE THREAD

**Issue by pubpharm** [HermannKroll/NarrativeIntelligence#200]
Study phase from ChEMBL is not uptodate, especially for "older" clinical studies (information is missing in ChEMBL) --> "?" is shown, confusing the users --> lets discuss this topic 

Feedback from the Roadshow Greifswald

**Comment by HermannKroll** [comment]
We should switch to Clinical Trials.gov as a data source:
For instance, ClinicalTrials.gov provides information in a tabular form, e.g.,
https://clinicaltrials.gov/search?cond=Myocardial%20Infarct&viewType=Table&term=ROSUVASTATIN

Build a pipeline that:
- Downloads Clinical Trial data
- Extracts the tabular information
- Performs entity linking for diseases (field: condition) and drugs (field: Interventions) 
- Extract all pairs of diseases and drugs plus the "highest" study phase (e.g. keep phase 4 over phase 3 if available)

Then integrate the extracted information into the Drug Overviews. Instead of showing ChEMBL information in Drug Overviews, show information from ChEMBL. Show the highest study phase if available. When a user clicks on such a phase, forward him to a corresponding search in ClinicalTrials.gov, e.g., 
https://clinicaltrials.gov/search?cond=Myocardial%20Infarct&viewType=Table&term=ROSUVASTATIN

**Comment by HermannKroll** [comment]
Solved and integrated.
